const c = (label, x, y, w, h, extra = {}) => ({ kind: "control", label, box: [x, y, w, h], ...extra });
const p = (label, x, y, w, h) => ({ kind: "panel", label, box: [x, y, w, h] });
const b = (label, x, y, w, h, extra = {}) => ({ kind: "bar", label, box: [x, y, w, h], ...extra });
const t = (label, x, y, w, h) => ({ kind: "label", label, box: [x, y, w, h] });

const S = {
  default: "Default",
  selected: "Selected",
  disabled: "Disabled",
  locked: "Locked",
  loading: "Loading",
  empty: "Empty",
  error: "Error",
  modal: "Modal",
  new: "New",
  offline: "Offline",
  warning: "Warning",
  critical: "Critical",
  hidden: "Hidden",
};

export const stateLabels = S;

export const demoLabels = {
  hudBar: "Resource bar with trailing fill",
  modal: "Modal open and close with focus return",
  tabs: "Tab page switch",
  grid: "Pooled grid scroll",
  focusList: "Focus frame travel",
  coach: "Coach mark pointer",
  pan: "Map pan and zoom",
  progressBar: "Determinate progress",
  typewriter: "Line reveal",
  scroll: "Credits scroll",
  unlock: "Node unlock",
  rank: "Rank swap",
  carousel: "Selection carousel",
};

export const elements = [
  {
    slug: "main-menu",
    demo: "focusList",
    states: ["default", "selected", "locked", "new", "loading", "offline"],
    unity: ["UIScreenRouter.cs", "UIScreen.cs", "SafeAreaFitter.cs"],
    cancel: "modal",
    regions: [
      t("Title", 8, 8, 40, 10),
      c("Continue", 8, 26, 26, 8),
      c("New game", 8, 36, 26, 8),
      c("Load", 8, 46, 26, 8, { lockable: true }),
      c("Settings", 8, 56, 26, 8),
      c("Quit", 8, 66, 26, 8),
      p("News and offers", 58, 26, 34, 48),
      t("Profile", 74, 8, 18, 8),
    ],
  },
  {
    slug: "in-game",
    demo: "hudBar",
    states: ["default", "warning", "critical", "hidden", "modal"],
    unity: ["HudResourceBar.cs", "SafeAreaFitter.cs", "UITween.cs"],
    cancel: "modal",
    regions: [
      b("Health", 6, 8, 30, 5, { fill: 1 }),
      b("Stamina", 6, 15, 22, 3.5, { fill: 0.8 }),
      p("Minimap", 78, 8, 16, 26),
      p("Objective", 72, 38, 22, 12),
      c("Ability 1", 38, 82, 7, 10),
      c("Ability 2", 46.5, 82, 7, 10),
      c("Ability 3", 55, 82, 7, 10),
      t("Interact prompt", 42, 56, 18, 6),
      t("Ammo 24 / 120", 74, 84, 20, 8),
    ],
  },
  {
    slug: "overlay",
    demo: "modal",
    states: ["default", "loading", "error", "modal"],
    unity: ["UIScreen.cs", "UIScreenRouter.cs", "UITween.cs"],
    cancel: "modal",
    regions: [
      p("Screen underneath", 6, 8, 88, 84),
      c("Open dialog", 40, 44, 20, 10),
      t("Party invite from Nightjar", 34, 58, 32, 6),
    ],
    modalText: ["Leave the party?", "Your queue position is kept for 60 s."],
  },
  {
    slug: "stats",
    demo: "hudBar",
    states: ["default", "selected", "locked"],
    unity: ["HudResourceBar.cs", "TabGroup.cs"],
    cancel: "back",
    regions: [
      t("Character stats", 6, 8, 40, 8),
      b("Strength", 6, 22, 40, 6, { fill: 0.72 }),
      b("Agility", 6, 31, 40, 6, { fill: 0.55 }),
      b("Intellect", 6, 40, 40, 6, { fill: 0.4 }),
      b("Armor", 6, 49, 40, 6, { fill: 0.64 }),
      p("Compared item", 56, 22, 36, 40),
      c("Equip", 56, 70, 16, 9),
      c("Compare", 76, 70, 16, 9),
    ],
  },
  {
    slug: "settings",
    demo: "tabs",
    states: ["default", "selected", "disabled", "loading"],
    unity: ["TabGroup.cs", "UIScreen.cs"],
    cancel: "modal",
    tabs: ["Video", "Audio", "Controls", "Accessibility"],
    regions: [
      c("Video", 6, 8, 18, 8),
      c("Audio", 26, 8, 18, 8),
      c("Controls", 46, 8, 18, 8),
      c("Accessibility", 66, 8, 22, 8),
      c("Apply", 64, 84, 14, 8),
      c("Revert", 80, 84, 14, 8),
    ],
    modalText: ["Keep display changes?", "Reverting in 15 s."],
  },
  {
    slug: "progress",
    demo: "progressBar",
    states: ["default", "new", "loading"],
    unity: ["HudResourceBar.cs", "UITween.cs"],
    cancel: "back",
    regions: [
      t("Level 23 reached", 30, 12, 40, 10),
      b("Experience", 20, 30, 60, 6, { fill: 0.3 }),
      p("Reward: Frost emblem", 20, 42, 28, 30),
      p("Next goal: Level 24", 52, 42, 28, 30),
      c("Continue", 40, 80, 20, 9),
    ],
  },
  {
    slug: "character",
    demo: "carousel",
    states: ["default", "selected", "locked", "loading"],
    unity: ["TabGroup.cs", "UITween.cs"],
    cancel: "back",
    regions: [
      c("Previous", 6, 42, 8, 14),
      c("Next", 86, 42, 8, 14),
      p("Details and loadout", 66, 10, 18, 70),
      c("Select", 40, 84, 20, 9),
    ],
    carousel: ["Ranger", "Engineer", "Medic", "Scout"],
  },
  {
    slug: "inventory",
    demo: "grid",
    states: ["default", "empty", "selected", "new", "locked", "loading"],
    unity: ["PooledGridView.cs", "InventorySlotCell.cs"],
    cancel: "back",
    regions: [
      t("Backpack 34 / 40", 6, 6, 30, 7),
      c("Sort", 40, 6, 12, 7),
      c("Filter", 54, 6, 12, 7),
      p("Item comparison", 70, 16, 24, 62),
      c("Use", 70, 82, 11, 8),
      c("Drop", 83, 82, 11, 8),
    ],
  },
  {
    slug: "tutorial",
    demo: "coach",
    states: ["default", "selected", "disabled"],
    unity: ["UIScreen.cs", "UITween.cs"],
    cancel: "back",
    regions: [
      c("Dodge", 70, 76, 10, 12),
      c("Attack", 82, 76, 10, 12),
      b("Health", 6, 8, 26, 5, { fill: 0.9 }),
      t("Press Dodge to roll through attacks", 30, 30, 40, 10),
      c("Skip tutorial", 6, 84, 16, 8),
    ],
  },
  {
    slug: "store",
    demo: "modal",
    states: ["default", "disabled", "loading", "error", "modal"],
    unity: ["UIScreen.cs", "UIScreenRouter.cs", "PooledGridView.cs"],
    cancel: "modal",
    regions: [
      t("Wallet 1,240 credits", 70, 6, 24, 7),
      c("Starter bundle 800", 6, 18, 28, 34),
      c("Season pass 1,000", 36, 18, 28, 34),
      c("Cosmetic crate 300", 66, 18, 28, 34),
      p("Offer ends in 2 days", 6, 58, 58, 12),
      c("Redeem code", 6, 82, 18, 9),
    ],
    modalText: ["Buy Season pass for 1,000 credits?", "Balance after purchase: 240."],
  },
  {
    slug: "quest",
    demo: "focusList",
    states: ["default", "selected", "new", "locked", "empty"],
    unity: ["PooledGridView.cs", "TabGroup.cs"],
    cancel: "back",
    regions: [
      c("Active", 6, 6, 14, 7),
      c("Completed", 22, 6, 16, 7),
      c("Find the signal tower", 6, 18, 36, 9),
      c("Escort the convoy", 6, 29, 36, 9),
      c("Repair the relay", 6, 40, 36, 9, { lockable: true }),
      p("Quest detail and rewards", 48, 18, 46, 56),
      c("Track", 48, 80, 14, 9),
      c("Show on map", 64, 80, 18, 9),
    ],
  },
  {
    slug: "map",
    demo: "pan",
    states: ["default", "selected", "disabled", "hidden"],
    unity: ["UITween.cs"],
    cancel: "back",
    regions: [
      c("Legend", 80, 6, 14, 8),
      c("Set waypoint", 80, 82, 14, 9),
      t("Zoom 1x", 6, 86, 14, 6),
    ],
  },
  {
    slug: "level-selection",
    demo: "focusList",
    states: ["default", "locked", "selected", "new"],
    unity: ["PooledGridView.cs", "UIScreen.cs"],
    cancel: "back",
    regions: [
      c("1-1", 8, 60, 10, 14),
      c("1-2", 24, 44, 10, 14),
      c("1-3", 40, 56, 10, 14),
      c("1-4", 56, 38, 10, 14),
      c("1-5", 72, 50, 10, 14, { lockable: true }),
      p("Level detail: 3 stars, best 02:41", 60, 8, 34, 22),
      c("Play", 84, 82, 10, 9),
    ],
  },
  {
    slug: "loading",
    demo: "progressBar",
    states: ["loading", "default", "error"],
    unity: ["HudResourceBar.cs", "UITween.cs"],
    cancel: "none",
    regions: [
      p("Key art area", 6, 8, 88, 56),
      t("Tip: parry resets your stamina", 6, 70, 60, 8),
      b("Loading", 6, 84, 60, 4, { fill: 0.2 }),
      t("Loading world", 70, 82, 24, 8),
    ],
  },
  {
    slug: "start-screen",
    demo: "progressBar",
    states: ["default", "loading", "error"],
    unity: ["UIScreen.cs", "UITween.cs"],
    cancel: "none",
    regions: [
      t("Game title", 30, 26, 40, 16),
      c("Press any button", 38, 64, 24, 9),
      b("Signing in", 38, 76, 24, 2.5, { fill: 0 }),
      t("Version and legal", 6, 88, 30, 6),
    ],
  },
  {
    slug: "dialogue",
    demo: "typewriter",
    states: ["default", "selected", "disabled"],
    unity: ["UIScreen.cs", "UITween.cs"],
    cancel: "back",
    line: "We lost the relay at dawn. If you go north, take the long road and stay off the ridge.",
    regions: [
      p("Speaker portrait", 6, 52, 14, 24),
      t("Mara, quartermaster", 22, 54, 30, 6),
      c("I will take the long road.", 60, 30, 34, 8),
      c("Why avoid the ridge?", 60, 40, 34, 8),
      c("Not now.", 60, 50, 34, 8),
      c("History", 84, 88, 10, 7),
    ],
  },
  {
    slug: "skill-tree",
    demo: "unlock",
    states: ["default", "locked", "selected", "disabled"],
    unity: ["UITween.cs", "TabGroup.cs"],
    cancel: "back",
    regions: [
      c("Root", 10, 44, 10, 14),
      c("Branch A", 30, 24, 10, 14),
      c("Branch B", 30, 64, 10, 14),
      c("Capstone", 50, 44, 10, 14, { lockable: true }),
      p("Node effect and cost", 66, 12, 28, 48),
      t("Points: 3", 66, 66, 28, 8),
      c("Unlock", 66, 80, 14, 9),
    ],
  },
  {
    slug: "credits",
    demo: "scroll",
    states: ["default", "selected"],
    unity: ["UITween.cs"],
    cancel: "back",
    regions: [
      c("Hold to speed up", 6, 86, 20, 8),
      c("Skip", 82, 86, 12, 8),
    ],
    lines: ["Directed by", "Lead design", "Engineering", "UI and UX", "Audio", "Localization", "Quality assurance", "Special thanks"],
  },
  {
    slug: "scoreboard",
    demo: "rank",
    states: ["default", "loading", "error"],
    unity: ["PooledGridView.cs", "UITween.cs"],
    cancel: "back",
    rows: ["Nightjar 2,410", "You 2,180", "Kestrel 1,960", "Wren 1,720"],
    regions: [
      t("Match 12:40 left", 6, 6, 30, 7),
      c("Team view", 70, 6, 24, 7),
    ],
  },
  {
    slug: "lobby",
    demo: "focusList",
    states: ["default", "loading", "selected", "error"],
    unity: ["UIScreenRouter.cs", "TabGroup.cs"],
    cancel: "modal",
    regions: [
      c("Slot 1: You", 6, 18, 20, 36),
      c("Slot 2: Nightjar", 28, 18, 20, 36),
      c("Slot 3: open", 50, 18, 20, 36),
      p("Mode: Squad, Region: Seoul", 74, 18, 20, 20),
      c("Loadout", 74, 44, 20, 10),
      c("Ready", 40, 80, 20, 10),
      t("Searching 00:42", 6, 84, 24, 7),
    ],
    modalText: ["Leave the lobby?", "Your party will be disbanded."],
  },
  {
    slug: "game-over",
    demo: "modal",
    states: ["default", "modal", "disabled"],
    unity: ["UIScreen.cs", "UIScreenRouter.cs", "UITween.cs"],
    cancel: "modal",
    autoOpen: true,
    regions: [
      p("Frozen gameplay", 6, 8, 88, 84),
      c("Show result", 40, 44, 20, 10),
    ],
    modalText: ["Defeated by the Warden", "Retry from checkpoint 3?"],
    modalActions: ["Retry", "Quit"],
  },
];

export const elementSlugs = elements.map((element) => element.slug);
